#!/usr/bin/env python
"""Phase-1 DF audit follow-up, step 1: radial conditional-velocity review.

Implements the plan `artifacts/df-phase1-audit/radial-conditional-velocity-audit-plan.md`
(output specification, sections 1-3).  For each capacity checkpoint it compares
the mass-weighted empirical velocity distribution of the held-out stars with
the model conditional distribution sampled AT THOSE SAME POSITIONS, aggregated
by the radius of those positions.

Protocol fixed by the plan (and by the phase-1 audit that produced the inputs):
  truth       held-out strict-common stars (n=242,725), per-particle mass
              weights; empirical distribution, not an analytic density
  positions   the same held-out positions for every model (full coverage, no
              stratified subsample), so truth and generation are paired
  K           K=4 draws per position, each generated sample weighted w_i/K;
              the base noise is shared across models (common random numbers);
              K-fold samples are NOT K independent positions
  bins        [0,10) [10,20) [20,30) [30,45) [45,60) [60,75) kpc; r >= 75 kpc
              is reported as a separate overflow bucket and never clipped in
  basis       v_r, v_theta, v_phi on the training frame (origin 0,0,0), km/s;
              samples with a degenerate basis are counted and excluded, never
              silently NaN
  distance    mass-weighted Wasserstein-1 on the UNCUT samples (never on the
              display histogram, so the display range cannot change a number)
  dispersion  centred standard deviation, not an RMS speed
  uncertainty position-level paired bootstrap (same resampling for truth and
              all models and all K draws), B=200, 95% percentile interval
  reference   truth random half-split W1: a finite-sample reference scale for
              the same bin, NOT an error bar and not subtracted
  cross-check the persisted full-coverage single draw (K=1) of the phase-1
              audit, same positions and weights
  sensitivity angular block bootstrap (cos-theta x phi cells within the bin)

Late-checkpoint stability: flow-19/20/21 of each run, same protocol, W1 only.

Outputs go to runs/halo12-radial-cv-20260917/: CSV (full precision), Markdown
(reading), JSON (protocol + all records) and one NPZ of the samples.  Figures
are a separate script that reads only those persisted arrays.

Run from the repo root (server, GPU host):
  CUDA_VISIBLE_DEVICES=<free gpu> python scripts/auriga/df_phase1_radial_cv_metrics.py
Self-test on synthetic data, no GPU and no checkpoint needed:
  python scripts/auriga/df_phase1_radial_cv_metrics.py --selftest
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import wasserstein_distance

# ----------------------------------------------------------------------
# 0. fixed constants and protocol metadata
# ----------------------------------------------------------------------
REPO = Path(__file__).resolve().parents[2]

# protocol from step 1 of the audit (regenerated by the run driver); the
# held-out positions, weights, bins and spherical coordinates all come from it
PROT_DIR = REPO / "runs" / "halo12-phase1-df-audit-20260916"
# persisted audit products (the K=1 full-coverage draw and the audit's own copy
# of the protocol, used only for the cross-check and an integrity assertion)
AUDIT_DIR = Path(os.environ.get(
    "RCV_AUDIT_DIR", "/localdisk/kosmos/my-deep-potential/runs/halo12-phase1-df-audit-20260916"))
OUT = REPO / "runs" / "halo12-radial-cv-20260917"

RUN_DIRS = {
    "w128": "runs/halo12-baseline",
    "w512": "runs/halo12-cap-w512",
    "w1024": "runs/halo12-cap-w1024",
}
MODELS = ["w128", "w512", "w1024"]
FINAL_CKPT = 21
LATE_CKPTS = [19, 20, 21]

COMP = ["vr", "vth", "vT"]
PAIRS = [("vr", "vth"), ("vr", "vT"), ("vth", "vT")]
KMS = 100.0          # code velocity unit -> km/s
KPC = 10.0           # code length unit -> kpc

# a position on the polar axis (R=0) has no v_theta/v_phi direction, and r=0
# has no v_r direction.  Threshold in code units (10^-6 code unit = 1e-5 kpc);
# anything below is flagged, excluded and counted -- never left as a silent NaN.
BASIS_MIN = 1e-6
# a correlation is only defined when both components have a non-zero spread
SIGMA_MIN = 1e-6

K_DRAWS = 4
B_BOOT = 200
B_SPLIT = 200
B_BLOCK = 50
SEED = 20260917
CHUNK_POS = 2048      # positions per jitted sampling call (K*CHUNK_POS samples)

COMP_LABEL = {"vr": "v_r", "vth": "v_theta", "vT": "v_phi"}
PAIR_LABEL = {("vr", "vth"): "v_r/v_theta", ("vr", "vT"): "v_r/v_phi",
              ("vth", "vT"): "v_theta/v_phi"}


# ----------------------------------------------------------------------
# 1. weighted statistics (no model, no JAX -- testable on synthetic input)
# ----------------------------------------------------------------------
def basis_flags(pos):
    """Degeneracy of the spherical velocity basis at these positions.

    R = 0 (polar axis) leaves v_theta/v_phi without a direction and r = 0
    leaves all three without one; both are reported, never silently NaN.
    """
    pos = np.asarray(pos, dtype=np.float64)
    r = np.linalg.norm(pos, axis=1)
    R = np.hypot(pos[:, 0], pos[:, 1])
    return dict(n_degenerate_r=int(np.count_nonzero(r <= BASIS_MIN)),
                n_degenerate_R=int(np.count_nonzero(R <= BASIS_MIN)),
                min_r=float(r.min()), min_R=float(R.min()))


def sph_vel(pos, vel_cart):
    """Cartesian -> spherical velocity basis (v_r, v_theta, v_phi).

    Same convention as the phase-1 audit (`utils.calc_coords`), origin (0,0,0),
    no rotation.  Returns the components plus the degeneracy flags, so callers
    can count and report rather than propagate a silent NaN.
    """
    pos = np.asarray(pos, dtype=np.float64)
    vel_cart = np.asarray(vel_cart, dtype=np.float64)
    x, y, z = pos[:, 0], pos[:, 1], pos[:, 2]
    vx, vy, vz = vel_cart[:, 0], vel_cart[:, 1], vel_cart[:, 2]
    r = np.linalg.norm(pos, axis=1)
    R = np.hypot(x, y)
    ok_r = r > BASIS_MIN
    ok_R = R > BASIS_MIN
    safe_r = np.where(ok_r, r, 1.0)
    safe_R = np.where(ok_R, R, 1.0)
    vr = (x * vx + y * vy + z * vz) / safe_r
    vth = (z * vr - safe_r * vz) / safe_R
    vT = (-vx * y + vy * x) / safe_R
    out = np.stack([np.where(ok_r, vr, np.nan),
                    np.where(ok_r & ok_R, vth, np.nan),
                    np.where(ok_r & ok_R, vT, np.nan)], axis=1)
    return out, basis_flags(pos)


def wmean(a, w):
    return float(np.sum(w * a) / np.sum(w))


def wstd(a, w):
    """Centred weighted standard deviation (not an RMS speed)."""
    mu = wmean(a, w)
    return float(np.sqrt(np.sum(w * (a - mu) ** 2) / np.sum(w)))


def wcorr(a, b, w):
    """Weighted Pearson correlation; NaN when either spread is degenerate."""
    ws = np.sum(w)
    ma = np.sum(w * a) / ws
    mb = np.sum(w * b) / ws
    da, db = a - ma, b - mb
    caa = np.sum(w * da * da) / ws
    cbb = np.sum(w * db * db) / ws
    if caa <= SIGMA_MIN ** 2 or cbb <= SIGMA_MIN ** 2:
        return float("nan")
    return float(np.sum(w * da * db) / ws / np.sqrt(caa * cbb))


def w1(a, wa, b, wb):
    """Mass-weighted Wasserstein-1 on the full, uncut samples (km/s in, km/s out)."""
    return float(wasserstein_distance(a, b, u_weights=wa, v_weights=wb))


def n_eff(w):
    return float(np.sum(w) ** 2 / np.sum(w ** 2))


def pct_ci(vals, lo=2.5, hi=97.5):
    v = np.asarray(vals, dtype=np.float64)
    v = v[np.isfinite(v)]
    if v.size == 0:
        return float("nan"), float("nan")
    return float(np.percentile(v, lo)), float(np.percentile(v, hi))


def component_stats(v_true, w_true, v_gen, w_gen, kms=KMS):
    """Per-component W1 / mean / centred sigma plus the three pair correlations.

    Every quantity is computed from the same samples; non-finite entries are
    excluded per component and counted by the caller through `n_invalid`.
    """
    out = {"n_invalid_rows": int(np.count_nonzero(~np.isfinite(v_gen).all(axis=1)))}
    for c, name in enumerate(COMP):
        t, g = v_true[:, c], v_gen[:, c]
        mt, mg = np.isfinite(t), np.isfinite(g)
        tt, wt = t[mt], w_true[mt]
        gg, wg = g[mg], w_gen[mg]
        rec = dict(n_invalid=int((~mg).sum()))
        if tt.size and gg.size:
            rec["w1"] = kms * w1(tt, wt, gg, wg)
            rec["mean_true"] = kms * wmean(tt, wt)
            rec["mean_gen"] = kms * wmean(gg, wg)
            rec["sigma_true"] = kms * wstd(tt, wt)
            rec["sigma_gen"] = kms * wstd(gg, wg)
            rec["dmean"] = rec["mean_gen"] - rec["mean_true"]
            rec["dsigma"] = rec["sigma_gen"] - rec["sigma_true"]
        else:
            for k in ("w1", "mean_true", "mean_gen", "sigma_true", "sigma_gen",
                      "dmean", "dsigma"):
                rec[k] = float("nan")
        out[name] = rec
    for (a, b) in PAIRS:
        ia, ib = COMP.index(a), COMP.index(b)
        ta, tb = v_true[:, ia], v_true[:, ib]
        ga, gb = v_gen[:, ia], v_gen[:, ib]
        mt = np.isfinite(ta) & np.isfinite(tb)
        mg = np.isfinite(ga) & np.isfinite(gb)
        rt = wcorr(ta[mt], tb[mt], w_true[mt]) if mt.any() else float("nan")
        rg = wcorr(ga[mg], gb[mg], w_gen[mg]) if mg.any() else float("nan")
        out[a + "|" + b] = dict(rho_true=rt, rho_gen=rg,
                                 drho=(rg - rt) if np.isfinite(rt) and np.isfinite(rg)
                                 else float("nan"),
                                 n_invalid=int((~mg).sum()))
    return out


def bootstrap_bin(v_true_b, w_true_b, gen_b, k, rng, b_boot):
    """Paired position bootstrap for one bin; returns arrays of length b_boot.

    `gen_b` is the (n_b, K, 3) generated block of ONE bin for one model.  The
    truth side is resampled with the same position draw, so the pairing the
    plan requires is kept exactly.
    """
    n_b = len(w_true_b)
    acc = {f"{q}|{n}": [] for q in ("w1", "dmean", "dsigma") for n in COMP}
    acc.update({f"drho|{a}|{b}": [] for (a, b) in PAIRS})
    for _ in range(b_boot):
        s = rng.integers(0, n_b, n_b)
        ws = w_true_b[s]
        rec = component_stats(v_true_b[s], ws, gen_b[s].reshape(-1, 3),
                              np.repeat(ws, k) / k)
        for n in COMP:
            acc[f"w1|{n}"].append(rec[n]["w1"])
            acc[f"dmean|{n}"].append(rec[n]["dmean"])
            acc[f"dsigma|{n}"].append(rec[n]["dsigma"])
        for (a, b) in PAIRS:
            acc[f"drho|{a}|{b}"].append(rec[a + "|" + b]["drho"])
    return {k_: (pct_ci(v)[0], pct_ci(v)[1]) for k_, v in acc.items()}


def block_bootstrap_bin(v_true_b, w_true_b, gen_b, k, block_b, rng, b_block):
    """Angular block bootstrap sensitivity: resample (cos-theta, phi) cells."""
    cells = np.unique(block_b)
    if block_b.size == 0 or cells.size < 2:
        return {n: (float("nan"), float("nan")) for n in COMP}, int(cells.size)
    members = [np.where(block_b == c)[0] for c in cells]
    acc = {n: [] for n in COMP}
    for _ in range(b_block):
        pick = rng.integers(0, cells.size, cells.size)
        sel = np.concatenate([members[i] for i in pick])
        ws = w_true_b[sel]
        rec = component_stats(v_true_b[sel], ws, gen_b[sel].reshape(-1, 3),
                              np.repeat(ws, k) / k)
        for n in COMP:
            acc[n].append(rec[n]["w1"])
    return {n: pct_ci(v) for n, v in acc.items()}, int(cells.size)


def truth_halfsplit_bin(v_true_b, w_true_b, rng, b_split):
    """W1 between two random halves of the same truth sample: reference scale.

    Each half has the same position count as the model comparison side only in
    the sense that it is the same stars; its own sample size is n_b/2, so this
    is a scale, not a lower bound and not something to subtract.
    """
    n_b = len(w_true_b)
    acc, n_eff_half = {n: [] for n in COMP}, []
    for _ in range(b_split):
        flip = rng.random(n_b) < 0.5
        if flip.all() or (~flip).all():
            continue
        a, b = np.where(flip)[0], np.where(~flip)[0]
        n_eff_half.append(n_eff(w_true_b[a]))
        for c, n in enumerate(COMP):
            xa, xb = v_true_b[a, c], v_true_b[b, c]
            ma, mb = np.isfinite(xa), np.isfinite(xb)
            if not ma.any() or not mb.any():
                continue
            acc[n].append(w1(xa[ma], w_true_b[a][ma], xb[mb], w_true_b[b][mb]) * KMS)
    out = {}
    for n in COMP:
        v = np.array(acc[n], dtype=np.float64)
        lo, hi = pct_ci(v)
        out[n] = dict(mean=float(np.nanmean(v)), sd=float(np.nanstd(v, ddof=1)),
                      lo=lo, hi=hi)
    out["n_eff_half"] = float(np.mean(n_eff_half)) if n_eff_half else float("nan")
    return out


def gen_halfsplit_bin(gen_b, rng, b_split):
    """W1 between the two K/2 halves of one model's draws: Monte-Carlo floor."""
    n_b, k, _ = gen_b.shape
    if k < 2:
        return {n: float("nan") for n in COMP}
    half = k // 2
    acc = {n: [] for n in COMP}
    for _ in range(b_split):
        perm = rng.permutation(k)
        a, b = gen_b[:, perm[:half]], gen_b[:, perm[half:2 * half]]
        wa = np.full(n_b, 1.0 / (n_b * half))
        for c, n in enumerate(COMP):
            xa, xb = a[:, :, c].reshape(-1), b[:, :, c].reshape(-1)
            ma, mb = np.isfinite(xa), np.isfinite(xb)
            if not ma.any() or not mb.any():
                continue
            acc[n].append(w1(xa[ma], np.repeat(wa, half)[ma],
                             xb[mb], np.repeat(wa, half)[mb]) * KMS)
    return {n: float(np.mean(v)) for n, v in acc.items()}


# ----------------------------------------------------------------------
# 2. model-dependent part: fresh conditional draws at the held-out positions
# ----------------------------------------------------------------------
def protocol_consistency(gen_k4, gen_k1, v_true, w_pos, ir, n_bins, k, rel_tol=0.15):
    """Agreement between two sample sets of the SAME model at the SAME positions.

    `gen_k4` maps a model name to its (n, K, 3) fresh spherical draws and
    `gen_k1` to its (n, 3) persisted single draw -- a different Monte-Carlo
    realization of the same conditional.  Every bin and component must agree to
    well inside that component's own spread.  Nothing here is a scientific
    statement: it is the guard that catches a sampling basis or unit mistake
    before any table is written.  Returns the worst mismatch per model (km/s).
    """
    worst = {}
    for m, g4 in gen_k4.items():
        w_ = 0.0
        for b in range(n_bins):
            mb = ir == b
            rec4 = component_stats(v_true[mb], w_pos[mb], g4[mb].reshape(-1, 3),
                                   np.repeat(w_pos[mb], k) / k)
            rec1 = component_stats(v_true[mb], w_pos[mb],
                                   gen_k1[m][mb].reshape(-1, 3), w_pos[mb])
            for n in COMP:
                d = abs(rec4[n]["w1"] - rec1[n]["w1"])
                tol = rel_tol * rec4[n]["sigma_true"]
                assert d < tol, (
                    f"{m} bin{b} {n}: the K={k} and K=1 samples of the same model"
                    f" disagree by {d:.2f} km/s (allowed {tol:.2f}); check the"
                    f" sampling basis and units before trusting any table")
                w_ = max(w_, d)
        worst[m] = w_
    return worst


def load_context():
    """Import the training-side stack and the loader (GPU host only)."""
    sys.path.insert(0, str(REPO / "scripts"))
    import equinox as eqx  # noqa: F401
    import jax  # noqa: F401
    import jax.numpy as jnp  # noqa: F401
    import fit_all  # noqa: E402
    return eqx, jax, jnp, fit_all


def sample_model_velocity(flow_dir, checkpoint, pos, k, z0, eqx, jax, jnp, fit_all,
                          chunk=CHUNK_POS, verify=True, tag=""):
    """K draws of v ~ p_theta(v|x) at every position, with explicit base noise.

    The base noise `z0` is passed in, so the SAME standard-normal draws are used
    for every checkpoint and every model (common random numbers); the transform
    is the one `ConditionalPhaseSpaceFlow.sample` uses, and the first chunk is
    cross-checked against that builtin sampler before anything is accepted.

    The flow works in CARTESIAN velocity; the spherical basis (v_r, v_theta,
    v_phi) is applied here, once, so that no caller can compare a Cartesian draw
    against the spherical truth columns.
    """
    flow = fit_all.load_flow(Path(flow_dir), checkpoint_index=checkpoint)
    cvf = flow.conditional_velocity_flow

    @eqx.filter_jit
    def stage(cvf_, z, x):
        cond = (x - cvf_.cond_mean) / cvf_.cond_std
        return jax.vmap(lambda z_, c_: cvf_.flow.bijection.transform(z_, condition=c_))(
            z.reshape(-1, 3), jnp.repeat(cond, k, axis=0)).reshape(-1, k, 3)

    if verify:
        key_chk = jax.random.key(11)
        n_chk = min(256, len(pos))
        z_chk = cvf.flow.base_dist.sample(key_chk, (n_chk,)).block_until_ready()
        explicit = np.asarray(stage(cvf, np.tile(np.asarray(z_chk)[:, None, :], (1, k, 1)),
                                    jnp.asarray(pos[:n_chk])))
        builtin = np.asarray(cvf.sample(key_chk, n_chk, condition=jnp.asarray(pos[:n_chk])))
        dmax = float(np.abs(explicit[:, 0] - builtin).max())
        print(f"  guard {tag}: max|explicit-builtin| = {dmax:.2e}", flush=True)
        assert dmax < 2e-2, f"explicit sampling does not match NormalizingFlow.sample for {tag}"

    out = np.empty((len(pos), k, 3), dtype=np.float32)
    for i in range(0, len(pos), chunk):
        sl = slice(i, min(i + chunk, len(pos)))
        out[sl] = np.asarray(stage(cvf, z0[sl], jnp.asarray(pos[sl])))
    flat, flags = sph_vel(np.repeat(np.asarray(pos), k, axis=0), out.reshape(-1, 3))
    del flow, cvf, stage
    jax.clear_caches()
    return flat.reshape(len(pos), k, 3), flags


# ----------------------------------------------------------------------
# 3. reading the protocol and the persisted audit cross-check
# ----------------------------------------------------------------------
def load_protocol():
    p = np.load(PROT_DIR / "eval_protocol.npz")
    prot = dict(
        eta_strict=p["eta_strict"],
        w_strict=np.asarray(p["w_strict"], dtype=np.float64),
        r=p["r_strict"], cth=p["cth_strict"], phi=p["phi_strict"],
        v_true=np.stack([p["vr_strict"], p["vth_strict"], p["vT_strict"]], axis=1),
        ir=p["ir_strict"], ic=p["ic_strict"], ip=p["ip_strict"],
        r_edges=p["r_edges"], cth_edges=p["cth_edges"], phi_edges=p["phi_edges"],
    )
    # integrity: the audit's own protocol copy must be the same evaluation set
    prot["audit_protocol_match"] = None
    alt = AUDIT_DIR / "eval_protocol.npz"
    if alt.exists():
        with np.load(alt) as q:
            same_eta = np.array_equal(q["eta_strict"], prot["eta_strict"])
            same_w = np.array_equal(q["w_strict"], p["w_strict"])
        prot["audit_protocol_match"] = bool(same_eta and same_w)
        assert prot["audit_protocol_match"], (
            f"regenerated protocol differs from {alt}; refusing to mix evaluation sets")
    return prot


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def choose_window(series):
    """Display window per component: the 0.05-99.95% range of the samples, km/s.

    The input is a mapping from component name to samples and must already be in
    km/s (the same key set is returned); the result is
    rounded outward to a multiple of 10 km/s.  It is persisted so the reported
    out-of-window mass fractions describe exactly the range that is drawn.  The
    window never enters a statistic: W1 always uses every sample.
    """
    win = {}
    for name in series:
        lo = np.nanpercentile(series[name], 0.05)
        hi = np.nanpercentile(series[name], 99.95)
        win[name] = [float(np.floor(lo / 10.0) * 10.0), float(np.ceil(hi / 10.0) * 10.0)]
    return win


def frac_out(v, w, lo, hi):
    ok = np.isfinite(v)
    tot = np.sum(w[ok])
    if tot <= 0:
        return float("nan")
    return float(np.sum(w[ok & (v < lo) | ok & (v > hi)]) / tot)


# ----------------------------------------------------------------------
# 4. markdown rendering (CSV keeps the digits, this is for reading)
# ----------------------------------------------------------------------
def md_table(header, rows, fmt=None):
    fmt = fmt or (lambda x: x)
    lines = ["| " + " | ".join(str(h) for h in header) + " |",
             "| " + " | ".join("---" for _ in header) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(str(fmt(x)) for x in row) + " |")
    return "\n".join(lines)


def fnum(x, nd=4, dash=True):
    if x is None:
        return "—" if dash else ""
    try:
        xf = float(x)
    except (TypeError, ValueError):
        return str(x)
    if not np.isfinite(xf):
        return "undefined" if dash else ""
    return f"{xf:.{nd}f}"


def fpm(mean, lo=None, hi=None, nd=4):
    if mean is None or not np.isfinite(float(mean)):
        return "undefined"
    if lo is None or hi is None or not (np.isfinite(lo) and np.isfinite(hi)):
        return f"{float(mean):.{nd}f}"
    return f"{float(mean):.{nd}f} [{float(lo):.{nd}f}, {float(hi):.{nd}f}]"


def build_markdown(bins, edges, stats, corr, support, ref, block, ckptstab, meta, window):
    bin_lab = [f"{edges[b][0]:.0f}–{edges[b][1]:.0f}" for b in range(len(edges))]
    L = []
    A = L.append
    A("# 径向条件速度审查：数值表\n")
    A(f"- 样本集：`k4` = 每个留出位置 K={meta['k_draws']} 次新采样（模型间共享基础噪声）；"
      f"`k1` = 相位一审计持久化的全覆盖单次配对采样\n"
      f"- 真值：留出 strict 公共集 {meta['n_true']} 颗星，质量加权；"
      f"bin 边界 kpc = {[f'{e[0]:.0f}' for e in edges] + [f'{edges[-1][1]:.0f}']}\n"
      f"- 速度单位 km/s；W1 用未裁剪样本；bootstrap B={meta['b_boot']}，区间为 95% percentile\n"
      f"- 显示窗口 km/s：" + "，".join(f"{k} [{v[0]:.0f}, {v[1]:.0f}]" for k, v in window.items()) + "\n")
    A("## 1. 分布距离 W1 (km/s)\n")
    for c in COMP:
        A(f"\n**{COMP_LABEL[c]}**\n")
        rows = [("真值半切参考",) + tuple(fnum(ref[b][c]["mean"], 4) if c in ref[b] else "—"
                                          for b in range(len(edges)))]
        for m in MODELS:
            rows.append((m,) + tuple(fpm(stats[(m, b, c, "k4")]["w1"],
                                         stats[(m, b, c, "k4")]["w1_lo"],
                                         stats[(m, b, c, "k4")]["w1_hi"], 4)
                                    for b in range(len(edges))))
        for m in MODELS:
            rows.append((m + " (k1)",) + tuple(fnum(stats[(m, b, c, "k1")]["w1"], 4)
                                               for b in range(len(edges))))
        A(md_table(["series"] + bin_lab, rows))
    A("\n## 2. 均值 (km/s)\n")
    for c in COMP:
        A(f"\n**{COMP_LABEL[c]}**：数据均值 / 模型均值 / 模型−数据\n")
        rows = [("数据",) + tuple(fnum(stats[(MODELS[0], b, c, "k4")]["mean_true"], 3)
                                 for b in range(len(edges)))]
        for m in MODELS:
            rows.append((m,)
                        + tuple(f"{fnum(stats[(m, b, c, 'k4')]['mean_gen'], 3)} "
                                f"({fnum(stats[(m, b, c, 'k4')]['dmean'], 3)})"
                                for b in range(len(edges))))
        A(md_table(["series"] + bin_lab, rows))
    A("\n## 3. 弥散 sigma (km/s，中心化标准差)\n")
    for c in COMP:
        A(f"\n**{COMP_LABEL[c]}**：数据 / 模型 / 模型−数据\n")
        rows = [("数据",) + tuple(fnum(stats[(MODELS[0], b, c, "k4")]["sigma_true"], 3)
                                 for b in range(len(edges)))]
        for m in MODELS:
            rows.append((m,)
                        + tuple(f"{fnum(stats[(m, b, c, 'k4')]['sigma_gen'], 3)} "
                                f"({fnum(stats[(m, b, c, 'k4')]['dsigma'], 3)})"
                                for b in range(len(edges))))
        A(md_table(["series"] + bin_lab, rows))
    A("\n## 4. 相关性（质量加权 Pearson，无量纲）\n")
    for pr in PAIRS:
        A(f"\n**{PAIR_LABEL[pr]}**：数据 / 模型 / 模型−数据\n")
        rows = [("数据",) + tuple(fnum(corr[(MODELS[0], b, pr, "k4")]["rho_true"], 3)
                                 for b in range(len(edges)))]
        for m in MODELS:
            rows.append((m,)
                        + tuple(f"{fnum(corr[(m, b, pr, 'k4')]['rho_gen'], 3)} "
                                f"({fnum(corr[(m, b, pr, 'k4')]['drho'], 3)})"
                                for b in range(len(edges))))
        A(md_table(["series"] + bin_lab, rows))
    A("\n## 5. 样本支持\n")
    for s in ("k4", "k1"):
        if (MODELS[0], 0, s) not in support:
            continue
        A(f"\n**sample = {s}**\n")
        rows = []
        for m in MODELS:
            sp = support[(m, 0, s)]
            rows.append((m + " N_true",) + tuple(str(support[(m, b, s)]["n_true"])
                                                 for b in range(len(edges))))
            rows.append((m + " N_eff",) + tuple(fnum(support[(m, b, s)]["n_eff"], 0)
                                                for b in range(len(edges))))
            rows.append((m + " 位置数",) + tuple(str(support[(m, b, s)]["n_positions"])
                                               for b in range(len(edges))))
            rows.append((m + " K",) + tuple(str(support[(m, b, s)]["k_draws"])
                                            for b in range(len(edges))))
            rows.append((m + " 质量占比",) + tuple(f"{100 * support[(m, b, s)]['mass_frac']:.2f}%"
                                                for b in range(len(edges))))
            rows.append((m + " 无效样本",) + tuple(str(support[(m, b, s)]["n_gen_invalid"])
                                                for b in range(len(edges))))
        A(md_table(["quantity"] + bin_lab, rows))
    A("\n## 6. 空间块重采样敏感性（W1 km/s，95% percentile）\n")
    for c in COMP:
        A(f"\n**{COMP_LABEL[c]}**\n")
        rows = [("bin " + bin_lab[b],) + tuple(
            fpm(stats[(m, b, c, "k4")]["w1"], block[(m, b, c)][0], block[(m, b, c)][1], 4)
            for m in MODELS) for b in range(len(edges))]
        A(md_table(["bin"] + MODELS, rows))
    A("\n## 7. 晚期 checkpoint 稳定性（W1 km/s，点估计）\n")
    for c in COMP:
        A(f"\n**{COMP_LABEL[c]}**\n")
        rows = []
        for m in MODELS:
            for ck in LATE_CKPTS:
                rows.append((f"{m} flow-{ck}",) + tuple(
                    fnum(ckptstab[(m, ck, b, c)], 4) for b in range(len(edges))))
        A(md_table(["series"] + bin_lab, rows))
    return "\n".join(L) + "\n"


# ----------------------------------------------------------------------
# 5. self-test on synthetic data (no JAX, no checkpoints)
# ----------------------------------------------------------------------
def selftest():
    rng = np.random.default_rng(7)
    n, k = 20000, K_DRAWS
    # radii spread over the whole bin range so every bin is populated; three
    # positions are put exactly on the polar axis / origin to exercise the
    # degeneracy flags and the invalid-sample path
    r_spread = rng.uniform(0.05, 7.2, n)
    u = rng.normal(size=(n, 3))
    u /= np.linalg.norm(u, axis=1, keepdims=True)
    pos = r_spread[:, None] * u
    pos[0] = [0.0, 0.0, 0.5]      # R = 0: v_theta, v_phi undefined
    pos[1] = [0.0, 0.0, 0.0]      # r = 0: all three undefined
    pos[2] = [1e-9, 0.0, 1.0]     # R below the threshold
    r = np.linalg.norm(pos, axis=1)
    r_edges = np.array([0.0, 1.0, 2.0, 3.0, 4.5, 6.0, 7.5])
    ir = np.clip(np.digitize(r, r_edges) - 1, 0, len(r_edges) - 2)
    w = rng.uniform(0.5, 1.5, n)
    assert min(np.bincount(ir, minlength=6)[:6]) > 1500
    mu = 0.4 * np.sin(r) + 0.1
    v_true = np.column_stack([mu + rng.normal(0, 1.2, n),
                              rng.normal(0, 1.0, n),
                              0.5 * rng.normal(0, 0.8, n) + 0.3 * mu])
    # model A: exactly the truth generator; model B: shifted mean and wider
    genA = np.empty((n, k, 3))
    genA[:, :, 0] = mu[:, None] + rng.normal(0, 1.2, (n, k))
    genA[:, :, 1] = rng.normal(0, 1.0, (n, k))
    genA[:, :, 2] = 0.5 * rng.normal(0, 0.8, (n, k)) + 0.3 * mu[:, None]
    genB = genA.copy()
    genB[:, :, 0] += 0.35
    genB[:, :, 1] *= 1.6
    rng2 = np.random.default_rng(11)
    idx_all = {b: np.where(ir == b)[0] for b in range(len(r_edges) - 1)}
    for b, idx in idx_all.items():
        if len(idx) < 100:
            continue
        vt, wt = v_true[idx], w[idx]
        rA = component_stats(vt, wt, genA[idx].reshape(-1, 3), np.repeat(wt, k) / k)
        rB = component_stats(vt, wt, genB[idx].reshape(-1, 3), np.repeat(wt, k) / k)
        # tolerance from the sampling noise of the two weighted means at this
        # bin's own position count, not a single global constant
        tol_mean = 4 * KMS * 1.2 * np.sqrt(1.0 / len(idx) + 1.0 / (len(idx) * k))
        tol_sigma = 4 * KMS * 1.2 * np.sqrt(0.5 / len(idx) + 0.5 / (len(idx) * k))
        assert rA["vr"]["w1"] < 0.5 * rB["vr"]["w1"], (b, rA["vr"]["w1"], rB["vr"]["w1"])
        assert abs(rA["vr"]["dmean"]) < tol_mean, (b, rA["vr"]["dmean"], tol_mean)
        assert rB["vr"]["dmean"] > 35.0 - tol_mean, (b, rB["vr"]["dmean"])
        assert abs(rA["vr"]["dsigma"]) < tol_sigma, (b, rA["vr"]["dsigma"], tol_sigma)
        assert rB["vth"]["dsigma"] > 20.0, rB["vth"]["dsigma"]
        assert np.isfinite(rA["vr|vth"]["rho_true"])
        boot = bootstrap_bin(vt, wt, genB[idx], k, rng2, 40)
        lo, hi = boot["dmean|vr"]
        assert lo < rB["vr"]["dmean"] < hi, (lo, rB["vr"]["dmean"], hi)
        lo, hi = boot["w1|vr"]
        assert lo <= rB["vr"]["w1"] <= hi, (lo, rB["vr"]["w1"], hi)
        ref = truth_halfsplit_bin(vt, wt, rng2, 30)
        assert ref["vr"]["mean"] > 0
        assert gen_halfsplit_bin(genB[idx], rng2, 20)["vr"] > 0
        blk, nb = block_bootstrap_bin(vt, wt, genB[idx], k,
                                      np.zeros(len(idx), dtype=int), rng2, 10)
        assert np.isnan(blk["vr"][0]) and nb == 1          # one cell -> undefined
        blk2, nb2 = block_bootstrap_bin(vt, wt, genB[idx], k,
                                        rng2.integers(0, 4, len(idx)), rng2, 15)
        assert nb2 == 4 and np.isfinite(blk2["vr"][0])
    # degenerate basis must be flagged, not silently NaN
    v_dg, flags = sph_vel(np.array([[0.0, 0.0, 1.0], [0.0, 0.0, 0.0]]),
                          np.array([[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]))
    assert flags["n_degenerate_R"] == 2 and flags["n_degenerate_r"] == 1
    assert np.isnan(v_dg[0, 1]) and np.isnan(v_dg[1, 0])
    # W1 against the analytic two-point case: shifting by d gives W1 = |d|
    a = np.array([0.0, 1.0])
    assert abs(w1(a, np.ones(2), a + 3.0, np.ones(2)) - 3.0) < 1e-12
    assert abs(n_eff(np.ones(9)) - 9.0) < 1e-12
    assert abs(wstd(np.array([0.0, 2.0]), np.ones(2)) - 1.0) < 1e-12
    assert abs(wcorr(np.array([0.0, 1.0, 2.0]), np.array([0.0, 1.0, 2.0]),
                     np.ones(3)) - 1.0) < 1e-12
    assert np.isnan(wcorr(np.array([1.0, 1.0]), np.array([0.0, 1.0]), np.ones(2)))
    print("selftest OK: weighting, W1, sigma, correlation, degeneracy, bootstrap,"
          " half-split reference, block sensitivity")
    return 0


# ----------------------------------------------------------------------
# 6. main
# ----------------------------------------------------------------------
def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--selftest", action="store_true",
                    help="run the synthetic-data checks (no GPU, no checkpoints) and exit")
    args = ap.parse_args(argv)
    if args.selftest:
        return selftest()

    os.environ.setdefault("XLA_PYTHON_CLIENT_PREALLOCATE", "false")
    t0 = time.time()
    OUT.mkdir(parents=True, exist_ok=True)

    print("=== RADIAL CONDITIONAL-VELOCITY REVIEW ===", flush=True)
    prot = load_protocol()
    eta, w_pos = prot["eta_strict"], prot["w_strict"]
    r, ir = prot["r"], prot["ir"]
    r_edges = prot["r_edges"]
    n_bins = len(r_edges) - 1
    pos = np.asarray(eta[:, :3], dtype=np.float64)
    v_true = prot["v_true"]
    edges = [(float(r_edges[b] * KPC), float(r_edges[b + 1] * KPC)) for b in range(n_bins)]

    # basis degeneracy on the held-out positions, reported before any metric
    deg = basis_flags(pos)
    overflow = int(np.count_nonzero(r >= r_edges[-1]))
    print(f"held-out positions: {len(pos)}   mass {w_pos.sum():.1f}", flush=True)
    print(f"basis: min r {deg['min_r']:.3e} code, min R {deg['min_R']:.3e} code;"
          f" degenerate r {deg['n_degenerate_r']}, degenerate R {deg['n_degenerate_R']};"
          f" r >= {r_edges[-1] * KPC:.0f} kpc (overflow, reported separately): {overflow}",
          flush=True)
    print("per-bin truth support:", flush=True)
    for b in range(n_bins):
        mb = ir == b
        print(f"  bin{b} [{edges[b][0]:.0f},{edges[b][1]:.0f}) kpc: n={int(mb.sum()):6d}"
              f"  N_eff={n_eff(w_pos[mb]):8.1f}  mass_frac={w_pos[mb].sum() / w_pos.sum():.4f}",
              flush=True)

    # The persisted full-coverage single draw of the same models, when the
    # phase-1 audit products are on this host.  It is a second Monte-Carlo
    # realization of the same conditional, so it both cross-checks the fresh
    # draws (protocol_consistency, run per model as soon as it is sampled) and
    # is reported as its own sample set.
    gen_k1 = {}
    for m in MODELS:
        f = AUDIT_DIR / f"model_{m}.npz"
        if not f.exists():
            print(f"WARNING: {f} missing -> no k1 comparison for {m}", flush=True)
            continue
        with np.load(f) as d:
            v_cart = d["vel_samples_all"]
        assert v_cart.shape[0] == len(pos), (m, v_cart.shape)
        gen_k1[m], _ = sph_vel(pos, v_cart)
        del v_cart
    if gen_k1:
        print(f"k1 comparison sample loaded for {sorted(gen_k1)}", flush=True)

    # ---------------------------------------------------------------- samples
    eqx = jax = jnp = fit_all = None
    rng = np.random.default_rng(SEED)
    z0 = rng.standard_normal((len(pos), K_DRAWS, 3))   # shared across models
    gen_late = {}
    for m in MODELS:
        flow_dir = REPO / RUN_DIRS[m] / "models" / "df" / "flow"
        for ck in LATE_CKPTS:
            if eqx is None:
                eqx, jax, jnp, fit_all = load_context()
            t1 = time.time()
            tag = f"{m} flow-{ck}"
            print(f"sampling {tag} (K={K_DRAWS}, full coverage) ...", flush=True)
            gen_late[(m, ck)], deg_gen = sample_model_velocity(
                flow_dir, ck, pos, K_DRAWS, z0, eqx, jax, jnp, fit_all, tag=tag)
            assert deg_gen["n_degenerate_r"] == deg["n_degenerate_r"]
            assert deg_gen["n_degenerate_R"] == deg["n_degenerate_R"]
            print(f"  {tag}: {time.time() - t1:.0f}s", flush=True)
            if ck == FINAL_CKPT and m in gen_k1:
                worst = protocol_consistency({m: gen_late[(m, ck)]}, gen_k1, v_true,
                                             w_pos, ir, n_bins, K_DRAWS)[m]
                print(f"  protocol consistency {m}: max |W1(k4)-W1(k1)| ="
                      f" {worst:.3f} km/s (inside 15% of each spread)", flush=True)

    gen = {(m, FINAL_CKPT): gen_late[(m, FINAL_CKPT)] for m in MODELS}

    # cross-check: the persisted full-coverage single draw of the phase-1 audit
    # (loaded before the sampling loop so the consistency check can run per model)

    # ------------------------------------------------------------- display window
    # km/s, the same unit as every reported number
    all_series = {n: v_true[:, c] * KMS for c, n in enumerate(COMP)}
    for c, n in enumerate(COMP):
        all_series[n] = np.concatenate([all_series[n]]
                                       + [gen[(m, FINAL_CKPT)][:, :, c].reshape(-1) * KMS
                                                          for m in MODELS])
    window = choose_window(all_series)
    print("display window (0.05-99.95% range, rounded outward to 10 km/s): "
          + ", ".join(f"{k} [{v[0]:.0f}, {v[1]:.0f}]" for k, v in window.items()), flush=True)


    # ------------------------------------------------------------- point estimates
    samples = {}
    for m in MODELS:
        samples[(m, "k4")] = gen[(m, FINAL_CKPT)]
        if m in gen_k1:
            samples[(m, "k1")] = gen_k1[m][:, None, :]

    stats, corr, support, ref, block = {}, {}, {}, {}, {}
    for b in range(n_bins):
        mb = ir == b
        vt_b, wt_b = v_true[mb], w_pos[mb]
        ref[b] = truth_halfsplit_bin(vt_b, wt_b, rng, B_SPLIT)
        for m in MODELS:
            for sname in ("k4", "k1"):
                if (m, sname) not in samples:
                    continue
                g = samples[(m, sname)][mb]
                k = g.shape[1]
                wg = np.repeat(wt_b, k) / k
                rec = component_stats(vt_b, wt_b, g.reshape(-1, 3), wg)
                boot = bootstrap_bin(vt_b, wt_b, g, k, rng, B_BOOT)
                for n in COMP:
                    lo, hi = boot[f"w1|{n}"]
                    dlo, dhi = boot[f"dmean|{n}"]
                    slo, shi = boot[f"dsigma|{n}"]
                    stats[(m, b, n, sname)] = dict(
                        **rec[n], w1_lo=lo, w1_hi=hi,
                        dmean_lo=dlo, dmean_hi=dhi, dsigma_lo=slo, dsigma_hi=shi,
                        frac_out_true=frac_out(vt_b[:, COMP.index(n)] * KMS, wt_b,
                                               *window[n]),
                        frac_out_gen=frac_out(g[:, :, COMP.index(n)].reshape(-1) * KMS, wg,
                                              *window[n]),
                        n_true=len(vt_b), n_eff=n_eff(wt_b), mass_frac=wt_b.sum() / w_pos.sum(),
                        n_positions=len(vt_b), k_draws=k,
                        n_gen=int(g[:, :, COMP.index(n)].size),
                        n_gen_invalid=rec[n]["n_invalid"])
                for pr in PAIRS:
                    r_ = rec[pr[0] + "|" + pr[1]]
                    dlo, dhi = boot[f"drho|{pr[0]}|{pr[1]}"]
                    corr[(m, b, pr, sname)] = dict(
                        rho_true=r_["rho_true"], rho_gen=r_["rho_gen"], drho=r_["drho"],
                        drho_lo=dlo, drho_hi=dhi,
                        corr_defined_true=bool(np.isfinite(r_["rho_true"])),
                        corr_defined_gen=bool(np.isfinite(r_["rho_gen"])),
                        n_true=len(vt_b), n_gen=int(g[:, :, 0].size))
                smp = dict(n_true=len(vt_b), n_eff=n_eff(wt_b), mass=float(wt_b.sum()),
                           mass_frac=float(wt_b.sum() / w_pos.sum()),
                           n_positions=len(vt_b), k_draws=k,
                           n_gen=int(g[:, :, 0].size),
                           n_gen_invalid=rec["n_invalid_rows"],
                           n_degenerate_basis=deg["n_degenerate_r"] + deg["n_degenerate_R"],
                           n_overflow_r=overflow)
                support[(m, b, sname)] = smp
            gm = gen_halfsplit_bin(gen[(m, FINAL_CKPT)][mb], rng, B_SPLIT)
            ref[b].setdefault("gen_half", {})[m] = gm
            # block sensitivity (final checkpoint, k4 only)
            cth_e, phi_e = prot["cth_edges"], prot["phi_edges"]
            cell = (np.clip(np.digitize(prot["cth"][mb], cth_e) - 1, 0, len(cth_e) - 2)
                    * (len(phi_e) - 1)
                    + np.clip(np.digitize(prot["phi"][mb], phi_e) - 1, 0, len(phi_e) - 2))
            blk, nb = block_bootstrap_bin(vt_b, wt_b, gen[(m, FINAL_CKPT)][mb], K_DRAWS,
                                          cell, rng, B_BLOCK)
            for n in COMP:
                block[(m, b, n)] = blk[n]
            block[(m, b, "n_blocks")] = nb
        print(f"bin{b}: point estimates + bootstrap done ({time.time() - t0:.0f}s)", flush=True)

    ckptstab = {}
    for m in MODELS:
        for ck in LATE_CKPTS:
            g_all = gen_late[(m, ck)]
            for b in range(n_bins):
                mb = ir == b
                rec = component_stats(v_true[mb], w_pos[mb], g_all[mb].reshape(-1, 3),
                                      np.repeat(w_pos[mb], K_DRAWS) / K_DRAWS)
                for n in COMP:
                    ckptstab[(m, ck, b, n)] = rec[n]["w1"]

    # ------------------------------------------------------------------ write
    rows = []
    for (m, b, n, sname), rec in stats.items():
        rows.append(dict(sample=sname, model=m, ckpt=f"flow-{FINAL_CKPT}", bin=b,
                         r_lo_kpc=edges[b][0], r_hi_kpc=edges[b][1], comp=n,
                         comp_label=COMP_LABEL[n],
                         **rec))
    pd.DataFrame(rows).to_csv(OUT / "rcv_stats.csv", index=False)

    rows = []
    for (m, b, pr, sname), rec in corr.items():
        rows.append(dict(sample=sname, model=m, ckpt=f"flow-{FINAL_CKPT}", bin=b,
                         r_lo_kpc=edges[b][0], r_hi_kpc=edges[b][1],
                         pair="|".join(pr), pair_label=PAIR_LABEL[pr], **rec))
    pd.DataFrame(rows).to_csv(OUT / "rcv_corr.csv", index=False)

    rows = []
    for (m, b, sname), rec in support.items():
        rows.append(dict(sample=sname, model=m, ckpt=f"flow-{FINAL_CKPT}", bin=b,
                         r_lo_kpc=edges[b][0], r_hi_kpc=edges[b][1], **rec))
    pd.DataFrame(rows).to_csv(OUT / "rcv_support.csv", index=False)

    rows = []
    for b in range(n_bins):
        for n in COMP:
            row = dict(bin=b, r_lo_kpc=edges[b][0], r_hi_kpc=edges[b][1], comp=COMP_LABEL[n],
                       comp_key=n,
                       truth_half_w1_kms=ref[b][n]["mean"], truth_half_w1_sd_kms=ref[b][n]["sd"],
                       truth_half_w1_lo=ref[b][n]["lo"], truth_half_w1_hi=ref[b][n]["hi"],
                       n_eff_half=ref[b]["n_eff_half"],
                       n_true=int((ir == b).sum()), n_eff=n_eff(w_pos[ir == b]))
            for m in MODELS:
                row[f"gen_half_w1_kms_{m}"] = ref[b]["gen_half"][m][n]
            rows.append(row)
    pd.DataFrame(rows).to_csv(OUT / "rcv_reference.csv", index=False)

    rows = []
    for (m, b, n), v in block.items():
        if n == "n_blocks":
            continue
        rows.append(dict(sample="k4", model=m, bin=b, r_lo_kpc=edges[b][0],
                         r_hi_kpc=edges[b][1], comp=n, comp_label=COMP_LABEL[n],
                         w1_kms=stats[(m, b, n, "k4")]["w1"],
                         w1_block_lo=v[0], w1_block_hi=v[1],
                         n_blocks=block[(m, b, "n_blocks")]))
    pd.DataFrame(rows).to_csv(OUT / "rcv_block_sensitivity.csv", index=False)

    rows = []
    for (m, ck, b, n), v in ckptstab.items():
        rows.append(dict(model=m, ckpt=f"flow-{ck}", bin=b, r_lo_kpc=edges[b][0],
                         r_hi_kpc=edges[b][1], comp=n, comp_label=COMP_LABEL[n], w1_kms=v,
                         n_true=int((ir == b).sum())))
    pd.DataFrame(rows).to_csv(OUT / "rcv_ckpt_stability.csv", index=False)

    np.savez_compressed(
        OUT / "rcv_arrays.npz",
        # every persisted velocity is in km/s (KMS), the same unit as every CSV
        # column, so a figure or a downstream check cannot mix code units in
        eta_strict=prot["eta_strict"], r_strict=r, ir_strict=ir,
        cth_strict=prot["cth"], phi_strict=prot["phi"], w_strict=w_pos,
        v_true=v_true * KMS, r_edges=r_edges, cth_edges=prot["cth_edges"],
        phi_edges=prot["phi_edges"], k_draws=np.int64(K_DRAWS),
        window_edges=np.array([window[n] for n in COMP]),
        comps=np.array(COMP),
        velocity_unit=np.array("km/s"), length_unit=np.array("kpc"),
        **{f"gen_k4_{m}": gen[(m, FINAL_CKPT)] * KMS for m in MODELS},
    )

    meta = dict(
        date="2026-09-17",
        plan="artifacts/df-phase1-audit/radial-conditional-velocity-audit-plan.md",
        inputs=dict(
            protocol_dir=str(PROT_DIR),
            audit_dir=str(AUDIT_DIR),
            protocol_sha256=sha256(PROT_DIR / "eval_protocol.npz"),
            audit_protocol_match=prot["audit_protocol_match"],
            runs={m: RUN_DIRS[m] for m in MODELS},
            checkpoints=dict(final=FINAL_CKPT, late=LATE_CKPTS),
        ),
        units=dict(length_kpc=KPC, velocity_kms=KMS,
                   note="v_r, v_theta, v_phi in km/s on the training frame (origin 0,0,0)"),
        protocol=dict(n_true=int(len(pos)), mass_total=float(w_pos.sum()),
                      k_draws=K_DRAWS, shared_base_noise_across_models=True,
                      weighting="per-particle mass; each generated sample weighted w_i/K",
                      bins_kpc=[[e[0], e[1]] for e in edges],
                      overflow_r_ge_kpc=float(r_edges[-1] * KPC), n_overflow=overflow,
                      basis_min_code=BASIS_MIN, sigma_min_code=SIGMA_MIN,
                      n_degenerate_r=deg["n_degenerate_r"],
                      n_degenerate_R=deg["n_degenerate_R"],
                      min_r_code=deg["min_r"], min_R_code=deg["min_R"],
                      b_boot=B_BOOT, b_split=B_SPLIT, b_block=B_BLOCK, seed=SEED,
                      window_kms=window,
                      caveat="one training seed per capacity point; the bootstrap"
                             " interval covers finite held-out positions only, not"
                             " training-seed scatter, and not the fixed-K Monte Carlo"
                             " error (reported separately as the generated half-split)"),
        per_bin_support=[dict(bin=b, **support[(MODELS[0], b, "k4")]) for b in range(n_bins)],
        reference_truth_halfsplit={b: {n: ref[b][n] for n in COMP} for b in range(n_bins)},
        generated_halfsplit={b: ref[b]["gen_half"] for b in range(n_bins)},
    )
    with open(OUT / "rcv_summary.json", "w") as f:
        json.dump(dict(meta=meta,
                       stats=[dict(model=m, bin=b, comp=n, comp_label=COMP_LABEL[n],
                                   sample=s, **v)
                              for (m, b, n, s), v in stats.items()],
                       corr=[dict(model=m, bin=b, pair="|".join(p),
                                  pair_label=PAIR_LABEL[p], sample=s, **v)
                             for (m, b, p, s), v in corr.items()],
                       ckpt_stability=[dict(model=m, ckpt=f"flow-{c}", bin=b,
                                            comp=n, comp_label=COMP_LABEL[n], w1_kms=v)
                                       for (m, c, b, n), v in ckptstab.items()]),
                  f, indent=1, default=lambda o: o.item() if hasattr(o, "item") else str(o))

    with open(OUT / "rcv_tables.md", "w") as f:
        f.write(build_markdown(list(range(n_bins)), edges, stats, corr, support, ref,
                               block, ckptstab, meta["protocol"], window))

    # ------------------------------------------------------------- stdout evidence
    print("\n=== W1 (km/s), k4, model | bin | 95% paired-bootstrap interval ===", flush=True)
    print("model   " + "".join(f"{edges[b][0]:.0f}-{edges[b][1]:.0f}".rjust(22)
                               for b in range(n_bins)))
    for m in MODELS:
        for n in COMP:
            cells = "".join((f"{stats[(m, b, n, 'k4')]['w1']:.4f}"
                             f"[{stats[(m, b, n, 'k4')]['w1_lo']:.4f},{stats[(m, b, n, 'k4')]['w1_hi']:.4f}]")
                            .rjust(22) for b in range(n_bins))
            print(f"{m:7s} {n:4s}" + cells, flush=True)
    print("\n=== truth half-split reference scale vs k4 W1 (km/s) ===", flush=True)
    for b in range(n_bins):
        print(f"  bin{b} [{edges[b][0]:.0f},{edges[b][1]:.0f}) kpc  truth-half "
              + "/".join(f"{ref[b][n]['mean']:.4f}" for n in COMP)
              + "   k4 w128 " + "/".join(f"{stats[('w128', b, n, 'k4')]['w1']:.4f}" for n in COMP)
              + "   k4 w1024 " + "/".join(f"{stats[('w1024', b, n, 'k4')]['w1']:.4f}" for n in COMP),
              flush=True)
    print("\n=== mean bias / sigma bias / correlation bias (k4, model - data) ===", flush=True)
    for b in range(n_bins):
        for m in MODELS:
            print(f"  bin{b} {m:5s} dmean " + "/".join(f"{stats[(m, b, n, 'k4')]['dmean']:+.3f}"
                                                        for n in COMP)
                  + "  dsigma " + "/".join(f"{stats[(m, b, n, 'k4')]['dsigma']:+.3f}" for n in COMP)
                  + "  drho " + "/".join(f"{corr[(m, b, p, 'k4')]['drho']:+.3f}" for p in PAIRS),
                  flush=True)
    print("\n=== late-checkpoint stability, W1(vr) (km/s) ===", flush=True)
    for m in MODELS:
        for b in range(n_bins):
            print(f"  {m:5s} bin{b}: " + "  ".join(
                f"flow-{ck} {ckptstab[(m, ck, b, 'vr')]:.4f}" for ck in LATE_CKPTS), flush=True)
    print("\n=== k1 cross-check: max |W1(k4) - W1(k1)| over bins/components ===", flush=True)
    for m in MODELS:
        if any((m, b, n, "k1") in stats for b in range(n_bins) for n in COMP):
            d = [abs(stats[(m, b, n, "k4")]["w1"] - stats[(m, b, n, "k1")]["w1"])
                 for b in range(n_bins) for n in COMP]
            print(f"  {m}: max {max(d):.4f} km/s, median {np.median(d):.4f}", flush=True)
    print(f"\noutputs under {OUT}  ({time.time() - t0:.0f}s total)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
